spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coursemanager?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: 85962216Wujq@
    type: com.alibaba.druid.pool.DruidDataSource